### PR TITLE
fix: commit Cargo.lock file

### PR DESCRIPTION
**Pull request by sethp**
Part of addressing issue #19.

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
Looks great! Let's do it

**Comment by sethp** [comment]
gonna try some git shenanigans, please hold...

**Comment by sethp** [comment]
huh, I guess github didn't expect me to merge just the base commit out-of-band. That ought to have updated the merge base for this PR, but did not: oh well, fiddling with the base branch seems to have updated it properly.

I intentionally used a somewhat outdated Cargo.lock over in `main`, so here's hoping this next part works....

**Comment by sethp** [comment]
ok, cool: and then a `cargo update` ought to give me a corpus to work from...

**Comment by dougli1sqrd** [comment]
That's cool

**Comment by sethp** [comment]
hooray, a green checkmark *inhales deeply* ahhhhhh, dopamine

**Pull request merged**
